// GENERATED by `php artisan sdk:generate` — do not edit by hand.

export interface Backup {
  id: number;
  server_id: number;
  storage_id: number;
  database_id: number | null;
  type: 'database' | 'file';
  path: string;
  interval: string;
  keep_backups: number;
  status: 'deleting' | null;
  enabled: boolean;
  server: Server | null;
}

export interface BackupFile {
  id: number;
  backup_id: number;
  name: string;
  size: number | null;
  status: 'created' | 'creating' | 'failed' | 'deleting' | 'restoring' | 'restored' | 'restore_failed' | 'delete_failed';
  restored_to: string | null;
}

export interface Command {
  id: number;
  site_id: number;
  name: string;
  command: string;
  site: Site | null;
  executions: CommandExecution[];
}

export interface CommandExecution {
  id: number;
  command_id: number;
  server_id: number;
  user_id: number;
  server_log_id: number | null;
  status: 'executing' | 'completed' | 'failed';
  server: Server | null;
}

export interface CronJob {
  id: number;
  server_id: number;
  site_id: number | null;
  name: string | null;
  command: string;
  user: string;
  frequency: string;
  hidden: boolean;
  status: 'creating' | 'ready' | 'deleting' | 'enabling' | 'disabling' | 'updating' | 'disabled';
  server: Server | null;
  site: Site | null;
}

export interface DNSProvider {
  id: number;
  user_id: number;
  name: string;
  provider: string;
  connected: boolean;
  project_id: number | null;
  project: Project | null;
}

export interface DNSRecord {
  id: number;
  domain_id: number;
  type: string;
  name: string;
  content: string;
  ttl: number;
  proxied: boolean;
  priority: number | null;
  domain: Domain | null;
}

export interface Database {
  id: number;
  server_id: number;
  name: string;
  collation: string;
  charset: string;
  status: 'ready' | 'creating' | 'failed' | 'deleting';
  server: Server | null;
}

export interface DatabaseUser {
  id: number;
  server_id: number;
  username: string;
  permission: 'read' | 'write' | 'admin';
  host: string;
  status: 'ready' | 'creating' | 'failed' | 'deleting';
  server: Server | null;
}

export interface Deployment {
  id: number;
  site_id: number;
  commit_id: string;
  status: 'deploying' | 'finished' | 'failed';
  release: string | null;
  active: boolean;
  site: Site | null;
}

export interface DeploymentScript {
  id: number;
  site_id: number;
  name: string;
  content: string;
  site: Site | null;
}

export interface Domain {
  id: number;
  dns_provider_id: number;
  user_id: number;
  project_id: number;
  domain: string;
  provider_domain_id: string;
  project: Project | null;
}

export interface File {
  id: number;
  user_id: number;
  server_id: number;
  server_user: string;
  path: string;
  type: string;
  name: string;
  size: number;
  links: number;
  owner: string;
  group: string;
  permissions: string;
}

export interface FirewallRule {
  id: number;
  server_id: number;
  name: string;
  type: string;
  protocol: string;
  port: string;
  source: string;
  mask: string | null;
  note: string;
  status: 'creating' | 'updating' | 'ready' | 'deleting' | 'failed';
  server: Server | null;
}

export interface GitHook {
  id: number;
  site_id: number;
  source_control_id: number;
  hook_id: string;
  site: Site | null;
}

export interface HostedDomain {
  id: number;
  site_id: number;
  domain: string;
  type: 'primary' | 'alias' | 'redirect';
  status: 'creating' | 'updating' | 'pending' | 'active' | 'inactive' | 'deleting';
  ssl_method: 'none' | 'letsencrypt' | 'custom';
  ssl_id: number | null;
  error: string | null;
  site: Site | null;
}

export interface IsolatedUser {
  id: number;
  server_id: number;
  username: string;
  server: Server | null;
}

export interface LoadBalancerServer {
  id: number;
  load_balancer_id: number;
  ip: string;
  port: number;
  weight: number;
  backup: boolean;
}

export interface Metric {
  id: number;
  server_id: number;
  load: number | null;
  memory_total: number | null;
  memory_used: number | null;
  disk_total: number | null;
  disk_used: number | null;
  cpu_cores: number | null;
  cpu_usage_percent: number | null;
  reboot_required: boolean | null;
  server: Server | null;
}

export interface NotificationChannel {
  id: number;
  user_id: number;
  provider: string;
  label: string;
  connected: boolean;
  project_id: number | null;
  project: Project | null;
}

export interface Plugin {
  id: number;
  name: string | null;
  version: string | null;
  description: string | null;
  repo: string | null;
  namespace: string;
  is_enabled: boolean;
  is_installed: boolean;
  updates_available: boolean;
  folder: string;
  username: string;
}

export interface PluginError {
  id: number;
  plugin_id: number;
  error_type: string;
  error_message: string;
  stack_trace: string | null;
  file: string | null;
  line: number | null;
  is_fatal: boolean;
  plugin: Plugin | null;
}

export interface Project {
  id: number;
  name: string;
}

export interface Redirect {
  id: number;
  site_id: number;
  from: string;
  to: string;
  mode: string;
  status: 'creating' | 'ready' | 'deleting' | 'failed';
  site: Site | null;
}

export interface Script {
  id: number;
  user_id: number;
  project_id: number | null;
  name: string;
  content: string;
  executions: ScriptExecution[];
}

export interface ScriptExecution {
  id: number;
  script_id: number;
  server_id: number | null;
  server_log_id: number;
  user: string;
  status: 'executing' | 'completed' | 'failed';
  server: Server | null;
}

export interface Server {
  id: number;
  project_id: number;
  name: string;
  ssh_user: string;
  ip: string;
  local_ip: string | null;
  port: number;
  os: 'ubuntu_18' | 'ubuntu_20' | 'ubuntu_22' | 'ubuntu_24';
  status: 'ready' | 'installing' | 'installation_failed' | 'disconnected' | 'updating';
  auto_update: boolean;
  project: Project | null;
}

export interface ServerIpAddress {
  id: number;
  server_id: number;
  ip: string;
  prefix_length: number;
  family: 'inet' | 'inet6';
  interface: string | null;
  type: 'public' | 'private' | 'unknown';
  status: 'configuring' | 'configured' | 'deleting' | 'failed';
  is_managed: boolean;
  is_primary: boolean;
  is_dynamic: boolean;
  server: Server | null;
}

export interface ServerLog {
  id: number;
  server_id: number;
  site_id: number | null;
  type: string;
  name: string;
  disk: string;
  is_remote: boolean;
  server: Server | null;
  site: Site | null;
}

export interface ServerProvider {
  id: number;
  user_id: number;
  profile: string;
  provider: string;
  connected: boolean;
  project_id: number | null;
  project: Project | null;
}

export interface ServerTemplate {
  id: number;
  user_id: number;
  name: string;
}

export interface Service {
  id: number;
  server_id: number;
  type: string;
  name: string;
  version: string;
  status: 'ready' | 'installing' | 'installation_failed' | 'uninstalling' | 'failed' | 'starting' | 'stopping' | 'restarting' | 'reloading' | 'stopped' | 'enabling' | 'disabling' | 'disabled';
  is_default: boolean;
  server: Server | null;
}

export interface Site {
  id: number;
  server_id: number;
  domain: string;
  web_directory: string;
  path: string;
  php_version: string;
  repository: string;
  branch: string;
  status: 'ready' | 'installing' | 'installation_failed' | 'deleting';
  port: number;
  server: Server | null;
}

export interface SourceControl {
  id: number;
  user_id: number;
  provider: string;
  profile: string;
  url: string | null;
  external_identifier: string | null;
  project_id: number | null;
  project: Project | null;
}

export interface SshKey {
  id: number;
  user_id: number;
  name: string;
}

export interface Ssl {
  id: number;
  site_id: number | null;
  server_id: number | null;
  domain_id: number | null;
  type: string;
  status: 'created' | 'creating' | 'deleting' | 'failed';
  is_wildcard: boolean;
  has_csr: boolean;
  email: string;
  site: Site | null;
  server: Server | null;
  domain: Domain | null;
}

export interface StorageProvider {
  id: number;
  user_id: number;
  profile: string;
  provider: string;
  project_id: number | null;
  project: Project | null;
}

export interface User {
  id: number;
  name: string;
  email: string;
  timezone: string;
  is_admin: boolean;
  current_project_id: number | null;
}

export interface UserProject {
  id: number;
  project_id: number;
  user_id: number | null;
  email: string | null;
  role: 'user' | 'admin' | 'owner';
  project: Project | null;
}

export interface Worker {
  id: number;
  server_id: number;
  site_id: number;
  name: string;
  command: string;
  user: string;
  auto_start: boolean;
  auto_restart: boolean;
  numprocs: number;
  status: 'running' | 'creating' | 'deleting' | 'failed' | 'starting' | 'stopping' | 'restarting' | 'stopped';
  error: string | null;
  server: Server | null;
  site: Site | null;
}

export interface Workflow {
  id: number;
  user_id: number | null;
  project_id: number | null;
  name: string;
  runs: WorkflowRun[];
}

export interface WorkflowRun {
  id: number;
  workflow_id: number | null;
  user_id: number | null;
  current_node_id: string | null;
  current_node_label: string | null;
  status: 'running' | 'completed' | 'failed';
}
