// GENERATED by `php artisan sdk:generate` — do not edit by hand.

export interface Database {
  id: number;
  server_id: number;
  name: string;
  collation: string;
  charset: string;
  status: 'ready' | 'creating' | 'failed' | 'deleting';
}

export interface Deployment {
  id: number;
  site_id: number;
  commit_id: string;
  status: 'deploying' | 'finished' | 'failed';
  release: string | null;
  active: boolean;
}

export interface Project {
  id: number;
  name: string;
}

export interface Server {
  id: number;
  project_id: number;
  name: string;
  ssh_user: string;
  ip: string;
  local_ip: string | null;
  port: number;
  os: 'ubuntu_18' | 'ubuntu_20' | 'ubuntu_22' | 'ubuntu_24';
  status: 'ready' | 'installing' | 'installation_failed' | 'disconnected' | 'updating';
  auto_update: boolean;
  project: Project | null;
}

export interface Service {
  id: number;
  server_id: number;
  type: string;
  name: string;
  version: string;
  status: 'ready' | 'installing' | 'installation_failed' | 'uninstalling' | 'failed' | 'starting' | 'stopping' | 'restarting' | 'reloading' | 'stopped' | 'enabling' | 'disabling' | 'disabled';
  is_default: boolean;
}

export interface Site {
  id: number;
  server_id: number;
  domain: string;
  web_directory: string;
  path: string;
  php_version: string;
  repository: string;
  branch: string;
  status: 'ready' | 'installing' | 'installation_failed' | 'deleting';
  port: number;
  server: Server | null;
}
