<?php

namespace App\Sdk\Generators;

use App\Sdk\Descriptors\ProjectionDescriptor;

final class PhpContractGenerator
{
    /**
     * @param  list<ProjectionDescriptor>  $descriptors
     * @return array<string, string>  [contractName => fileContents]
     */
    public function generate(array $descriptors): array
    {
        $files = [];

        foreach ($descriptors as $descriptor) {
            $files[$descriptor->contractName] = $this->file($descriptor);
        }

        return $files;
    }

    private function file(ProjectionDescriptor $descriptor): string
    {
        $lines = [];
        $lines[] = '<?php';
        $lines[] = '';
        $lines[] = 'namespace Vito\\Plugin\\Contracts;';
        $lines[] = '';
        $lines[] = '/**';
        $lines[] = ' * GENERATED by `php artisan sdk:generate` — do not edit by hand.';

        if ($descriptor->properties !== []) {
            $lines[] = ' *';
            foreach ($descriptor->properties as $property) {
                $lines[] = ' * @property-read '.$property->phpDocType.' $'.$property->name;
            }
        }

        $lines[] = ' */';

        if ($descriptor->methods === []) {
            $lines[] = 'interface '.$descriptor->contractName.' {}';
            $lines[] = '';

            return implode("\n", $lines);
        }

        $lines[] = 'interface '.$descriptor->contractName;
        $lines[] = '{';

        $methods = [];
        foreach ($descriptor->methods as $method => $returnType) {
            $methods[] = '    public function '.$method.'(): '.$returnType.';';
        }
        $lines[] = implode("\n\n", $methods);

        $lines[] = '}';
        $lines[] = '';

        return implode("\n", $lines);
    }
}
