<?php

namespace App\Sdk\Generators;

use App\Sdk\Descriptors\ProjectionDescriptor;

final class TypeScriptGenerator
{
    /**
     * @param  list<ProjectionDescriptor>  $descriptors
     */
    public function generate(array $descriptors): string
    {
        $lines = [];
        $lines[] = '// GENERATED by `php artisan sdk:generate` — do not edit by hand.';
        $lines[] = '';

        if ($descriptors === []) {
            $lines[] = 'export {};';
            $lines[] = '';

            return implode("\n", $lines);
        }

        $blocks = [];
        foreach ($descriptors as $descriptor) {
            $blocks[] = $this->interface($descriptor);
        }
        $lines[] = implode("\n\n", $blocks);
        $lines[] = '';

        return implode("\n", $lines);
    }

    private function interface(ProjectionDescriptor $descriptor): string
    {
        $lines = [];
        $lines[] = 'export interface '.$descriptor->contractName.' {';

        foreach ($descriptor->properties as $property) {
            $lines[] = '  '.$property->name.': '.$property->tsType.';';
        }

        $lines[] = '}';

        return implode("\n", $lines);
    }
}
