<?php

namespace Vito\Plugin\Contracts;

/**
 * GENERATED by `php artisan sdk:generate` — do not edit by hand.
 *
 * @property-read int $id
 * @property-read int $server_id
 * @property-read int $storage_id
 * @property-read int|null $database_id
 * @property-read \BackedEnum&\Vito\Plugin\Contracts\VitoEnum $type
 * @property-read string $path
 * @property-read string $interval
 * @property-read int $keep_backups
 * @property-read \BackedEnum&\Vito\Plugin\Contracts\VitoEnum|null $status
 * @property-read bool $enabled
 * @property-read \Vito\Plugin\Contracts\Server|null $server
 */
interface Backup
{
    public function isCustomInterval(): bool;
}
