<?php

namespace Vito\Plugin\Contracts;

/**
 * GENERATED by `php artisan sdk:generate` — do not edit by hand.
 *
 * @property-read int $id
 * @property-read int $backup_id
 * @property-read string $name
 * @property-read int|null $size
 * @property-read \BackedEnum&\Vito\Plugin\Contracts\VitoEnum $status
 * @property-read string|null $restored_to
 */
interface BackupFile
{
    public function isAvailable(): bool;

    public function isLocal(): bool;

    public function path(): string;
}
