<?php

namespace Vito\Plugin\Contracts;

/**
 * GENERATED by `php artisan sdk:generate` — do not edit by hand.
 *
 * @property-read int $id
 * @property-read int $command_id
 * @property-read int $server_id
 * @property-read int $user_id
 * @property-read int|null $server_log_id
 * @property-read \BackedEnum&\Vito\Plugin\Contracts\VitoEnum $status
 * @property-read \Vito\Plugin\Contracts\Server|null $server
 */
interface CommandExecution
{
    public function getContent(): string;
}
