<?php

namespace Vito\Plugin\Contracts;

/**
 * GENERATED by `php artisan sdk:generate` — do not edit by hand.
 *
 * @property-read int $id
 * @property-read int $site_id
 * @property-read string $name
 * @property-read string $command
 * @property-read \Vito\Plugin\Contracts\Site|null $site
 * @property-read array<int, \Vito\Plugin\Contracts\CommandExecution> $executions
 */
interface Command {}
