<?php

namespace Vito\Plugin\Contracts;

/**
 * GENERATED by `php artisan sdk:generate` — do not edit by hand.
 *
 * @property-read int $id
 * @property-read int $server_id
 * @property-read int|null $site_id
 * @property-read string|null $name
 * @property-read string $command
 * @property-read string $user
 * @property-read string $frequency
 * @property-read bool $hidden
 * @property-read \BackedEnum&\Vito\Plugin\Contracts\VitoEnum $status
 * @property-read \Vito\Plugin\Contracts\Server|null $server
 * @property-read \Vito\Plugin\Contracts\Site|null $site
 */
interface CronJob
{
    public function frequencyLabel(): string;

    public function isEnabled(): bool;

    public function isDisabled(): bool;
}
