<?php

namespace Vito\Plugin\Contracts;

/**
 * GENERATED by `php artisan sdk:generate` — do not edit by hand.
 *
 * @property-read int $id
 * @property-read int $server_id
 * @property-read string $name
 * @property-read string $collation
 * @property-read string $charset
 * @property-read \App\Enums\DatabaseStatus $status
 */
interface Database {}
