<?php

namespace Vito\Plugin\Contracts;

/**
 * GENERATED by `php artisan sdk:generate` — do not edit by hand.
 *
 * @property-read int $id
 * @property-read int $site_id
 * @property-read string $commit_id
 * @property-read \App\Enums\DeploymentStatus $status
 * @property-read string|null $release
 * @property-read bool $active
 */
interface Deployment {}
