<?php

namespace Vito\Plugin\Contracts;

/**
 * GENERATED by `php artisan sdk:generate` — do not edit by hand.
 *
 * @property-read int $id
 * @property-read int $site_id
 * @property-read string $commit_id
 * @property-read \BackedEnum&\Vito\Plugin\Contracts\VitoEnum $status
 * @property-read string|null $release
 * @property-read bool $active
 * @property-read \Vito\Plugin\Contracts\Site|null $site
 */
interface Deployment {}
