<?php

namespace Vito\Plugin\Contracts;

/**
 * GENERATED by `php artisan sdk:generate` — do not edit by hand.
 *
 * @property-read int $id
 * @property-read int $domain_id
 * @property-read string $type
 * @property-read string $name
 * @property-read string $content
 * @property-read int $ttl
 * @property-read bool $proxied
 * @property-read int|null $priority
 * @property-read \Vito\Plugin\Contracts\Domain|null $domain
 */
interface DNSRecord {}
