<?php

namespace Vito\Plugin\Contracts;

/**
 * GENERATED by `php artisan sdk:generate` — do not edit by hand.
 *
 * @property-read int $id
 * @property-read int $dns_provider_id
 * @property-read int $user_id
 * @property-read int $project_id
 * @property-read string $domain
 * @property-read string $provider_domain_id
 * @property-read \Vito\Plugin\Contracts\Project|null $project
 */
interface Domain {}
