<?php

namespace Vito\Plugin\Contracts;

/**
 * GENERATED by `php artisan sdk:generate` — do not edit by hand.
 *
 * @property-read int $id
 * @property-read int $user_id
 * @property-read int $server_id
 * @property-read string $server_user
 * @property-read string $path
 * @property-read string $type
 * @property-read string $name
 * @property-read int $size
 * @property-read int $links
 * @property-read string $owner
 * @property-read string $group
 * @property-read string $permissions
 */
interface File
{
    public function getFilePath(): string;

    public function isExtractable(): bool;
}
