<?php

namespace Vito\Plugin\Contracts;

/**
 * GENERATED by `php artisan sdk:generate` — do not edit by hand.
 *
 * @property-read int $id
 * @property-read int $server_id
 * @property-read string $name
 * @property-read string $type
 * @property-read string $protocol
 * @property-read string $port
 * @property-read string $source
 * @property-read string|null $mask
 * @property-read string $note
 * @property-read \BackedEnum&\Vito\Plugin\Contracts\VitoEnum $status
 * @property-read \Vito\Plugin\Contracts\Server|null $server
 */
interface FirewallRule {}
