<?php

namespace Vito\Plugin\Contracts;

/**
 * GENERATED by `php artisan sdk:generate` — do not edit by hand.
 *
 * @property-read int $id
 * @property-read int $site_id
 * @property-read int $source_control_id
 * @property-read string $hook_id
 * @property-read \Vito\Plugin\Contracts\Site|null $site
 */
interface GitHook {}
