<?php

namespace Vito\Plugin\Contracts;

/**
 * GENERATED by `php artisan sdk:generate` — do not edit by hand.
 *
 * @property-read int $id
 * @property-read int $site_id
 * @property-read string $domain
 * @property-read \BackedEnum&\Vito\Plugin\Contracts\VitoEnum $type
 * @property-read \BackedEnum&\Vito\Plugin\Contracts\VitoEnum $status
 * @property-read \BackedEnum&\Vito\Plugin\Contracts\VitoEnum $ssl_method
 * @property-read int|null $ssl_id
 * @property-read string|null $error
 * @property-read \Vito\Plugin\Contracts\Site|null $site
 */
interface HostedDomain {}
