<?php

namespace Vito\Plugin\Contracts;

/**
 * GENERATED by `php artisan sdk:generate` — do not edit by hand.
 *
 * @property-read int $id
 * @property-read int $server_id
 * @property-read string $username
 * @property-read \Vito\Plugin\Contracts\Server|null $server
 */
interface IsolatedUser {}
