<?php

namespace Vito\Plugin\Contracts;

/**
 * GENERATED by `php artisan sdk:generate` — do not edit by hand.
 *
 * @property-read int $id
 * @property-read int $load_balancer_id
 * @property-read string $ip
 * @property-read int $port
 * @property-read int $weight
 * @property-read bool $backup
 */
interface LoadBalancerServer {}
