<?php

namespace Vito\Plugin\Contracts;

/**
 * GENERATED by `php artisan sdk:generate` — do not edit by hand.
 *
 * @property-read int $id
 * @property-read int $server_id
 * @property-read float|null $load
 * @property-read float|null $memory_total
 * @property-read float|null $memory_used
 * @property-read float|null $disk_total
 * @property-read float|null $disk_used
 * @property-read int|null $cpu_cores
 * @property-read float|null $cpu_usage_percent
 * @property-read bool|null $reboot_required
 * @property-read \Vito\Plugin\Contracts\Server|null $server
 */
interface Metric {}
