<?php

namespace Vito\Plugin\Contracts;

/**
 * GENERATED by `php artisan sdk:generate` — do not edit by hand.
 *
 * @property-read int $id
 * @property-read int $plugin_id
 * @property-read string $error_type
 * @property-read string $error_message
 * @property-read string|null $stack_trace
 * @property-read string|null $file
 * @property-read int|null $line
 * @property-read bool $is_fatal
 * @property-read \Vito\Plugin\Contracts\Plugin|null $plugin
 */
interface PluginError {}
