<?php

namespace Vito\Plugin\Contracts;

/**
 * GENERATED by `php artisan sdk:generate` — do not edit by hand.
 *
 * @property-read int $id
 * @property-read string|null $name
 * @property-read string|null $version
 * @property-read string|null $description
 * @property-read string|null $repo
 * @property-read string $namespace
 * @property-read bool $is_enabled
 * @property-read bool $is_installed
 * @property-read bool $updates_available
 * @property-read string $folder
 * @property-read string $username
 */
interface Plugin {}
