<?php

namespace Vito\Plugin\Contracts;

/**
 * GENERATED by `php artisan sdk:generate` — do not edit by hand.
 *
 * @property-read int $id
 * @property-read int $site_id
 * @property-read string $from
 * @property-read string $to
 * @property-read string $mode
 * @property-read \BackedEnum&\Vito\Plugin\Contracts\VitoEnum $status
 * @property-read \Vito\Plugin\Contracts\Site|null $site
 */
interface Redirect {}
