<?php

namespace Vito\Plugin\Contracts;

/**
 * GENERATED by `php artisan sdk:generate` — do not edit by hand.
 *
 * @property-read int $id
 * @property-read int $user_id
 * @property-read int|null $project_id
 * @property-read string $name
 * @property-read string $content
 * @property-read array<int, \Vito\Plugin\Contracts\ScriptExecution> $executions
 */
interface Script {}
