<?php

namespace Vito\Plugin\Contracts;

/**
 * GENERATED by `php artisan sdk:generate` — do not edit by hand.
 *
 * @property-read int $id
 * @property-read int $server_id
 * @property-read int|null $site_id
 * @property-read string $type
 * @property-read string $name
 * @property-read string $disk
 * @property-read bool $is_remote
 * @property-read \Vito\Plugin\Contracts\Server|null $server
 * @property-read \Vito\Plugin\Contracts\Site|null $site
 */
interface ServerLog {}
