<?php

namespace Vito\Plugin\Contracts;

/**
 * GENERATED by `php artisan sdk:generate` — do not edit by hand.
 *
 * @property-read int $id
 * @property-read int $server_id
 * @property-read string $ip
 * @property-read int $prefix_length
 * @property-read \BackedEnum&\Vito\Plugin\Contracts\VitoEnum $family
 * @property-read string|null $interface
 * @property-read \BackedEnum&\Vito\Plugin\Contracts\VitoEnum $type
 * @property-read \BackedEnum&\Vito\Plugin\Contracts\VitoEnum $status
 * @property-read bool $is_managed
 * @property-read bool $is_primary
 * @property-read bool $is_dynamic
 * @property-read \Vito\Plugin\Contracts\Server|null $server
 */
interface ServerIpAddress {}
