<?php

namespace Vito\Plugin\Contracts;

/**
 * GENERATED by `php artisan sdk:generate` — do not edit by hand.
 *
 * @property-read int $id
 * @property-read int $server_id
 * @property-read string $type
 * @property-read string $name
 * @property-read string $version
 * @property-read \App\Enums\ServiceStatus $status
 * @property-read bool $is_default
 */
interface Service {}
