<?php

namespace Vito\Plugin\Contracts;

/**
 * GENERATED by `php artisan sdk:generate` — do not edit by hand.
 *
 * @property-read int $id
 * @property-read int $user_id
 * @property-read string $profile
 * @property-read string $provider
 * @property-read bool $connected
 * @property-read int|null $project_id
 * @property-read \Vito\Plugin\Contracts\Project|null $project
 */
interface ServerProvider {}
