<?php

namespace Vito\Plugin\Contracts;

/**
 * GENERATED by `php artisan sdk:generate` — do not edit by hand.
 *
 * @property-read int $id
 * @property-read int $project_id
 * @property-read string $name
 * @property-read string $ssh_user
 * @property-read string $ip
 * @property-read string|null $local_ip
 * @property-read int $port
 * @property-read \App\Enums\OperatingSystem $os
 * @property-read \App\Enums\ServerStatus $status
 * @property-read bool $auto_update
 * @property-read \Vito\Plugin\Contracts\Project|null $project
 */
interface Server
{
    public function isReady(): bool;

    public function getSshUser(): string;
}
