<?php

namespace Vito\Plugin\Contracts;

/**
 * GENERATED by `php artisan sdk:generate` — do not edit by hand.
 *
 * @property-read int $id
 * @property-read int $server_id
 * @property-read string $domain
 * @property-read string $web_directory
 * @property-read string $path
 * @property-read string $php_version
 * @property-read string $repository
 * @property-read string $branch
 * @property-read \BackedEnum&\Vito\Plugin\Contracts\VitoEnum $status
 * @property-read int $port
 * @property-read \Vito\Plugin\Contracts\Server|null $server
 */
interface Site
{
    public function getUrl(): string;

    public function isReady(): bool;
}
