<?php

namespace Vito\Plugin\Contracts;

/**
 * GENERATED by `php artisan sdk:generate` — do not edit by hand.
 *
 * @property-read int $id
 * @property-read int $user_id
 * @property-read string $provider
 * @property-read string $profile
 * @property-read string|null $url
 * @property-read string|null $external_identifier
 * @property-read int|null $project_id
 * @property-read \Vito\Plugin\Contracts\Project|null $project
 */
interface SourceControl
{
    public function isGithubApp(): bool;
}
