<?php

namespace Vito\Plugin\Contracts;

/**
 * GENERATED by `php artisan sdk:generate` — do not edit by hand.
 *
 * @property-read int $id
 * @property-read int|null $site_id
 * @property-read int|null $server_id
 * @property-read int|null $domain_id
 * @property-read string $type
 * @property-read \BackedEnum&\Vito\Plugin\Contracts\VitoEnum $status
 * @property-read bool $is_wildcard
 * @property-read bool $has_csr
 * @property-read string $email
 * @property-read \Vito\Plugin\Contracts\Site|null $site
 * @property-read \Vito\Plugin\Contracts\Server|null $server
 * @property-read \Vito\Plugin\Contracts\Domain|null $domain
 */
interface Ssl {}
