<?php

namespace Vito\Plugin\Contracts;

/**
 * GENERATED by `php artisan sdk:generate` — do not edit by hand.
 *
 * @property-read int $id
 * @property-read string $name
 * @property-read string $email
 * @property-read string $timezone
 * @property-read bool $is_admin
 * @property-read int|null $current_project_id
 */
interface User
{
    public function isAdmin(): bool;
}
