<?php

namespace Vito\Plugin\Contracts;

/**
 * GENERATED by `php artisan sdk:generate` — do not edit by hand.
 *
 * @property-read int $id
 * @property-read int $project_id
 * @property-read int|null $user_id
 * @property-read string|null $email
 * @property-read \BackedEnum&\Vito\Plugin\Contracts\VitoEnum $role
 * @property-read \Vito\Plugin\Contracts\Project|null $project
 */
interface UserProject {}
