<?php

namespace Vito\Plugin\Contracts;

/**
 * GENERATED by `php artisan sdk:generate` — do not edit by hand.
 *
 * @property-read int $id
 * @property-read int|null $workflow_id
 * @property-read int|null $user_id
 * @property-read string|null $current_node_id
 * @property-read string|null $current_node_label
 * @property-read \BackedEnum&\Vito\Plugin\Contracts\VitoEnum $status
 */
interface WorkflowRun
{
    public function getLogContent(): string;
}
