<?php

namespace Vito\Plugin\Contracts;

/**
 * GENERATED by `php artisan sdk:generate` — do not edit by hand.
 *
 * @property-read int $id
 * @property-read int|null $user_id
 * @property-read int|null $project_id
 * @property-read string $name
 * @property-read array<int, \Vito\Plugin\Contracts\WorkflowRun> $runs
 */
interface Workflow {}
