<?php

namespace Vito\Plugin\Contracts;

/**
 * GENERATED by `php artisan sdk:generate` — do not edit by hand.
 *
 * @property-read int $id
 * @property-read int $server_id
 * @property-read int $site_id
 * @property-read string $name
 * @property-read string $command
 * @property-read string $user
 * @property-read bool $auto_start
 * @property-read bool $auto_restart
 * @property-read int $numprocs
 * @property-read \BackedEnum&\Vito\Plugin\Contracts\VitoEnum $status
 * @property-read string|null $error
 * @property-read \Vito\Plugin\Contracts\Server|null $server
 * @property-read \Vito\Plugin\Contracts\Site|null $site
 */
interface Worker
{
    public function isSiteBootstrap(): bool;
}
